rollback = [
    "I really liked the {} fashion image you provided. Based on that, ",
    "The {} fashion image caught my eye—it’s just my style. Based on that, ",
    "That {} fashion image was exactly what I was looking for. Based on that, ",
    "I'm a fan of the {} fashion image you shared. Based on that, ",
    "The {} image you gave perfectly matched my fashion taste. Based on that, ",
    "I was impressed by the {} fashion image—it felt spot on. Based on that, ",
    "That {} outfit image resonated with my aesthetic. Based on that, ",
    "The {} fashion concept was very appealing to me. Based on that, ",
    "I loved the fashion vibe of the {} image you showed. Based on that, ",
    "The {} fashion sample stood out as my favorite. Based on that, ",
    "My favorite so far is the {} fashion image—it was great. Based on that, ",
    "The {} fashion design you generated was totally my style. Based on that, ",
    "I connected with the fashion mood of that {} image. Based on that, ",
    "I appreciated the fashion direction of the {} image. Based on that, ",
    "The fashion look in the {} image really worked for me. Based on that, ",
    "Out of everything, the {} fashion image felt the most authentic to my taste. Based on that, ",
    "The {} fashion illustration aligned perfectly with my preferences. Based on that, ",
    "The original fashion image had the exact vibe I wanted. Based on that, ",
    "I felt that the {} fashion image had the best style match. Based on that, ",
    "The {} image had a strong fashion impact on me—I liked it most. Based on that, ",
    "That very {} image had a style I truly connected with. Based on that, ",
    "I liked the look and feel of the {} fashion image the best. Based on that, ",
    "The fashion shown in the {} image really spoke to me. Based on that, ",
    "The {} image captured the exact aesthetic I love. Based on that, ",
    "I was drawn to the fashion elements in the {} picture. Based on that, ",
    "That {} outfit image felt the most relevant to my taste. Based on that, ",
    "I felt like the {} fashion image truly represented what I wanted. Based on that, ",
    "Among all, the {} one stood out for its stylish appeal. Based on that, ",
    "I liked the fashion direction shown in the {} concept. Based on that, ",
    "The {} fashion image was both stylish and inspiring. Based on that, ",
    "That {} image nailed the style I had in mind. Based on that, ",
    "The {} image reflected a strong sense of personal style I admire. Based on that, ",
    "The fashion in the {} image fit my taste better than the rest. Based on that, ",
    "I loved the elegance of the {} fashion concept. Based on that, ",
    "The {} outfit looked effortlessly cool—just how I like it. Based on that, ",
    "The fashion mood in the {} image caught my attention. Based on that, ",
    "The {} fashion design felt modern and stylish—just right. Based on that, ",
    "I loved the aesthetic direction in the very {} fashion image. Based on that, ",
    "The fashion in the {} image really matched my expectations. Based on that, ",
    "That {} image had the perfect combination of colors and style. Based on that, ",
    "I appreciated the style and creativity in the {} picture. Based on that, ",
    "The {} image gave off the right fashion-forward vibe. Based on that, ",
    "I was really happy with the look shown in the {} outfit. Based on that, ",
    "The original image matched the tone I was going for. Based on that, ",
    "The {} fashion sketch stood out as bold and tasteful. Based on that, ",
    "I liked the styling choices made in the {} concept. Based on that, ",
    "The {} image set a strong tone—it was just right. Based on that, ",
    "I still think the {} fashion image is the best of the bunch. Based on that, ",
]

combination = [
    "Keep the {} of the {} fashion image and the {} of the {} fashion image ",
    "Preserve the {} from the {} fashion image and combine it with the {} from the {} fashion image ",
    "Retain the {} of the {} fashion image while using the {} from the {} fashion image ",
    "Use the {} from the {} fashion image and maintain the {} of the {} fashion image ",
    "Incorporate the {} of the {} fashion image and the {} style of the {} fashion image ",
    "Merge the {} shown in the {} fashion image with the {} of the {} fashion image ",
    "Take the {} of the {} fashion image and blend it with the {} from the {} fashion image ",
    "Adopt the {} seen in the {} fashion image keeping the {} from the {} fashion image ",
    "Hold onto the {} of the {} fashion image and pair it with the {} of the {} fashion image ",
    "Stick to the {} in the {} fashion image and fuse it with the {} from the {} fashion image ",
    "Combine the {} from the {} fashion image with the {} of the {} fashion image ",
    "Keep the {} element of the {} fashion image and the {} element from the {} fashion image ",
    "Preserve the {} characteristic of the {} fashion image along with the {} of the {} fashion image ",
    "Maintain the {} featured in the {} fashion image and incorporate the {} of the {} fashion image ",
    "Stick with the {} from the {} fashion image and add the {} of the {} fashion image ",
    "Emphasize the {} in the {} fashion image and the {} shown in the {} fashion image ",
    "Focus on the {} from the {} fashion image and the {} seen in the {} fashion image ",
    "Use the {} showcased in the {} fashion image and preserve the {} in the {} fashion image ",
    "Retain the {} details of the {} fashion image and match them with the {} from the {} fashion image ",
    "Merge the {} traits of the {} fashion image with the {} from the {} fashion image ",
    "Bring the {} from the {} fashion image together with the {} of the {} fashion image ",
    "Blend the {} of the {} fashion image into the {} of the {} fashion image ",
    "Transfer the {} found in the {} fashion image and apply it to the {} of the {} fashion image ",
    "Infuse the {} of the {} fashion image with the {} from the {} fashion image ",
    "Add the {} from the {} fashion image while maintaining the {} in the {} fashion image ",
    "Keep both the {} of the {} fashion image and the {} of the {} fashion image intact,",
    "Use the {} as seen in the {} fashion image along with the {} shown in the {} fashion image ",
    "Draw from the {} in the {} fashion image and the {} in the {} fashion image ",
    "Fuse the {} from the {} fashion image and the {} from the {} fashion image ",
    "Let the {} of the {} fashion image guide the combination with the {} of the {} fashion image ",
    "Highlight the {} in the {} fashion image while incorporating the {} from the {} fashion image ",
    "Keep consistent the {} of the {} fashion image and the {} from the {} fashion image ",
    "Borrow the {} from the {} fashion image and mix it with the {} in the {} fashion image ",
    "Carry over the {} used in the {} fashion image to pair with the {} of the {} fashion image ",
    "Make use of the {} from the {} fashion image while preserving the {} of the {} fashion image ",
    "Take inspiration from the {} of the {} fashion image and the {} in the {} fashion image ",
    "Draw the {} from the {} fashion image and maintain the {} from the {} fashion image ",
    "Use the {} style of the {} fashion image. keeping the {} look of the {} fashion image ",
    "Keep the {} and {} styles from the {} and {} fashion images respectively,",
    "Preserve the {} influence of the {} fashion image with the {} from the {} fashion image ",
    "Apply the {} from the {} fashion image while holding onto the {} of the {} fashion image ",
    "Keep a mix of the {} found in the {} fashion image and the {} in the {} fashion image ",
    "Design with the {} of the {} fashion image. and the {} shown in the {} fashion image ",
    "Base the design on the {} from the {} fashion image and the {} of the {} fashion image ",
    "Hold the {} in the {} fashion image and the {} visible in the {} fashion image ",
    "Incorporate the {} aesthetics of the {} fashion image with the {} style from the {} fashion image ",
    "Stay true to the {} in the {} fashion image while adding the {} of the {} fashion image ",
    "Let the {} in the {} fashion image remain and integrate the {} of the {} fashion image ",
    "Balance the {} from the {} fashion image and the {} of the {} fashion image ",
]
