rollback = [
    "I like the fashion image at turn {n_turn}. Based on all the fashion attributes of this image, please find a new image that also incorporates the {new_attr} attribute.",
    "I like the fashion image at turn {n_turn}. Please find an image that reflects all of its fashion attributes plus a new {new_attr} attribute.",
    "The fashion image at turn {n_turn} appeals to me. Find an image that maintains all its fashion attributes and includes the new {new_attr} feature.",
    "I’m fond of the fashion image from turn {n_turn}. Using all its fashion characteristics, find a new image that incorporates the {new_attr} attribute as well.",
    "I like the fashion image at turn {n_turn}. Based on all its fashion features, please locate an image that adds the {new_attr} attribute.",
    "The fashion image at turn {n_turn} is appealing to me. Find a new image that preserves its fashion attributes and adds the {new_attr} trait.",
    "I really like the fashion image from turn {n_turn}. Using its full set of fashion attributes, find an image that includes the {new_attr} property.",
    "I enjoy the fashion image at turn {n_turn}. Please locate an image that keeps all its fashion attributes and introduces the {new_attr} characteristic.",
    "The fashion image at turn {n_turn} pleases me. Find an image that contains all its fashion features and incorporates the {new_attr} attribute.",
    "I am fond of the fashion image from turn {n_turn}. Please find a new image that retains its fashion details plus the {new_attr} element.",
    "I like the fashion image at turn {n_turn}. Based on its complete fashion profile, find an image with an added {new_attr} attribute.",
    "I appreciate the fashion image at turn {n_turn}. Please locate an image that maintains all attributes and adds the {new_attr} feature.",
    "The fashion image at turn {n_turn} impresses me. Find an image that reflects all its fashion elements plus the {new_attr} characteristic.",
    "I am fond of the fashion image at turn {n_turn}. Using all its style details, find an image that also has the {new_attr} property.",
    "I really like the fashion image at turn {n_turn}. Find an image that keeps all fashion traits and adds the {new_attr} attribute.",
    "I enjoy the fashion image from turn {n_turn}. Please locate an image that contains all its fashion characteristics and introduces the {new_attr} trait.",
    "The fashion image at turn {n_turn} appeals to me. Find a new image that preserves its fashion features and includes the {new_attr} attribute.",
    "I like the fashion image at turn {n_turn}. Using all its fashion details, please find an image with an added {new_attr} element.",
    "I admire the fashion image at turn {n_turn}. Please find a new image that retains its attributes and incorporates the {new_attr} feature.",
    "I appreciate the fashion image from turn {n_turn}. Find an image that reflects all fashion aspects plus the {new_attr} trait.",
    "The fashion image at turn {n_turn} pleases me. Find a new image that keeps all its style details and adds the {new_attr} attribute.",
    "I like the fashion image at turn {n_turn}. Please locate an image that maintains all attributes and introduces the {new_attr} characteristic.",
    "I am fond of the fashion image at turn {n_turn}. Using its complete fashion traits, find an image that also has the {new_attr} feature.",
    "I really enjoy the fashion image from turn {n_turn}. Find an image that contains all its fashion attributes plus the {new_attr} property.",
    "The fashion image at turn {n_turn} is appealing. Find a new image that keeps its fashion details and includes the {new_attr} attribute.",
    "I like the fashion image at turn {n_turn}. Please find an image that preserves all style elements and adds the {new_attr} trait.",
    "I admire the fashion image at turn {n_turn}. Using all its fashion attributes, find an image that includes the {new_attr} characteristic.",
    "The fashion image at turn {n_turn} impresses me. Find a new image that maintains its fashion profile and incorporates the {new_attr} feature.",
    "I like the fashion image from turn {n_turn}. Please locate an image that keeps all its fashion elements and introduces the {new_attr} attribute.",
    "I am fond of the fashion image at turn {n_turn}. Using all fashion traits, find an image that also has the {new_attr} property.",
    "I really like the fashion image at turn {n_turn}. Find an image that retains all style features and adds the {new_attr} characteristic.",
    "The fashion image at turn {n_turn} pleases me. Find a new image that preserves all its fashion details and includes the {new_attr} trait.",
    "I like the fashion image at turn {n_turn}. Please locate an image that reflects all attributes and introduces the {new_attr} element.",
    "I appreciate the fashion image from turn {n_turn}. Find an image that keeps all its fashion characteristics and adds the {new_attr} feature.",
    "The fashion image at turn {n_turn} is impressive. Find a new image that retains all its style traits plus the {new_attr} attribute.",
    "I like the fashion image at turn {n_turn}. Using all its fashion details, please find an image that also incorporates the {new_attr} characteristic.",
    "I admire the fashion image from turn {n_turn}. Find an image that maintains all attributes and adds the {new_attr} property.",
    "The fashion image at turn {n_turn} appeals to me. Find a new image that contains all fashion features and includes the {new_attr} trait.",
    "I like the fashion image at turn {n_turn}. Please locate an image that keeps all style elements and introduces the {new_attr} feature.",
    "I really enjoy the fashion image from turn {n_turn}. Find an image that preserves all its fashion attributes and adds the {new_attr} characteristic.",
    "The fashion image at turn {n_turn} impresses me. Find a new image that reflects all style traits plus the {new_attr} property.",
    "I like the fashion image at turn {n_turn}. Using all its fashion features, find an image that also has the {new_attr} element.",
    "I appreciate the fashion image from turn {n_turn}. Please find an image that maintains all its attributes and includes the {new_attr} trait.",
    "The fashion image at turn {n_turn} is appealing. Find a new image that contains all fashion details and introduces the {new_attr} characteristic.",
    "I like the fashion image at turn {n_turn}. Please locate an image that preserves all its style features and adds the {new_attr} property.",
    "I really like the fashion image from turn {n_turn}. Find an image that keeps all fashion traits and incorporates the {new_attr} element."
]

combination = [
    "Maintain the {old_attr1} and {old_attr2} of the fashion image at turn {n_turn}, adding a change that includes the {new_attr} attribute.",
    "Keep the {old_attr1} and {old_attr2} of the fashion image at turn {n_turn}, while adding a change with the {new_attr} property.",
    "Preserve the {old_attr1} and {old_attr2} in the fashion image at turn {n_turn}, introducing a change containing the {new_attr} feature.",
    "Hold the {old_attr1} and {old_attr2} attributes of the fashion image at turn {n_turn}, adding a variation that includes the {new_attr} trait.",
    "Retain the {old_attr1} and {old_attr2} aspects of the fashion image at turn {n_turn}, while including a change with the {new_attr} characteristic.",
    "Keep the {old_attr1} and {old_attr2} fashion traits at turn {n_turn}, but add a change that contains the {new_attr} element.",
    "Maintain the {old_attr1} and {old_attr2} style features of the fashion image at turn {n_turn}, adding a change including the {new_attr} attribute.",
    "Preserve the {old_attr1} and {old_attr2} qualities of the fashion image at turn {n_turn}, while incorporating a change with the {new_attr} feature.",
    "Hold the {old_attr1} and {old_attr2} fashion elements at turn {n_turn}, then add a change with the {new_attr} characteristic.",
    "Retain the {old_attr1} and {old_attr2} attributes at turn {n_turn}, while making a change containing the {new_attr} trait.",
    "Keep the {old_attr1} and {old_attr2} looks of the fashion image at turn {n_turn}, adding a change that features the {new_attr} property.",
    "Maintain the {old_attr1} and {old_attr2} aspects of the fashion image at turn {n_turn}, but add a change that includes the {new_attr} element.",
    "Preserve the {old_attr1} and {old_attr2} traits in the fashion image at turn {n_turn}, introducing a change with the {new_attr} characteristic.",
    "Hold the {old_attr1} and {old_attr2} features of the fashion image at turn {n_turn}, while adding a change containing the {new_attr} attribute.",
    "Retain the {old_attr1} and {old_attr2} qualities at turn {n_turn}, including a change that has the {new_attr} trait.",
    "Keep the {old_attr1} and {old_attr2} traits of the fashion image at turn {n_turn}, adding a change that contains the {new_attr} element.",
    "Maintain the {old_attr1} and {old_attr2} characteristics at turn {n_turn}, while adding a change including the {new_attr} feature.",
    "Preserve the {old_attr1} and {old_attr2} fashion qualities of the image at turn {n_turn}, then add a change with the {new_attr} attribute.",
    "Hold the {old_attr1} and {old_attr2} fashion aspects at turn {n_turn}, while including a change with the {new_attr} characteristic.",
    "Retain the {old_attr1} and {old_attr2} looks of the fashion image at turn {n_turn}, adding a change featuring the {new_attr} trait.",
    "Keep the {old_attr1} and {old_attr2} style attributes at turn {n_turn}, while adding a change that contains the {new_attr} element.",
    "Maintain the {old_attr1} and {old_attr2} fashion features at turn {n_turn}, introducing a change that includes the {new_attr} attribute.",
    "Preserve the {old_attr1} and {old_attr2} elements of the fashion image at turn {n_turn}, adding a change that incorporates the {new_attr} trait.",
    "Hold the {old_attr1} and {old_attr2} qualities in the fashion image at turn {n_turn}, while adding a change containing the {new_attr} feature.",
    "Retain the {old_attr1} and {old_attr2} traits at turn {n_turn}, adding a change that includes the {new_attr} characteristic.",
    "Keep the {old_attr1} and {old_attr2} elements of the fashion image at turn {n_turn}, while adding a change that features the {new_attr} property.",
    "Maintain the {old_attr1} and {old_attr2} attributes of the fashion image at turn {n_turn}, with a change containing the {new_attr} trait.",
    "Preserve the {old_attr1} and {old_attr2} fashion aspects at turn {n_turn}, introducing a change including the {new_attr} element.",
    "Hold the {old_attr1} and {old_attr2} style features at turn {n_turn}, while adding a change with the {new_attr} characteristic.",
    "Retain the {old_attr1} and {old_attr2} traits in the fashion image at turn {n_turn}, adding a change that contains the {new_attr} attribute.",
    "Keep the {old_attr1} and {old_attr2} qualities at turn {n_turn}, while adding a change that includes the {new_attr} feature.",
    "Maintain the {old_attr1} and {old_attr2} characteristics at turn {n_turn}, introducing a change with the {new_attr} trait.",
    "Preserve the {old_attr1} and {old_attr2} fashion elements at turn {n_turn}, while adding a change containing the {new_attr} property.",
    "Hold the {old_attr1} and {old_attr2} style traits at turn {n_turn}, adding a change that features the {new_attr} element.",
    "Retain the {old_attr1} and {old_attr2} attributes of the fashion image at turn {n_turn}, while including a change with the {new_attr} characteristic.",
    "Keep the {old_attr1} and {old_attr2} features at turn {n_turn}, adding a change that contains the {new_attr} attribute.",
    "Maintain the {old_attr1} and {old_attr2} fashion traits of the image at turn {n_turn}, with a change that includes the {new_attr} feature.",
    "Preserve the {old_attr1} and {old_attr2} fashion qualities at turn {n_turn}, introducing a change containing the {new_attr} element.",
    "Hold the {old_attr1} and {old_attr2} style features at turn {n_turn}, while adding a change with the {new_attr} trait.",
    "Retain the {old_attr1} and {old_attr2} characteristics at turn {n_turn}, adding a change that features the {new_attr} property.",
    "Keep the {old_attr1} and {old_attr2} traits in the fashion image at turn {n_turn}, while including a change containing the {new_attr} attribute.",
    "Maintain the {old_attr1} and {old_attr2} elements of the fashion image at turn {n_turn}, adding a change that contains the {new_attr} characteristic.",
    "Preserve the {old_attr1} and {old_attr2} fashion aspects at turn {n_turn}, while adding a change including the {new_attr} trait.",
    "Hold the {old_attr1} and {old_attr2} qualities of the fashion image at turn {n_turn}, with a change that features the {new_attr} element.",
    "Retain the {old_attr1} and {old_attr2} style attributes at turn {n_turn}, adding a change that includes the {new_attr} property.",
    "Keep the {old_attr1} and {old_attr2} fashion traits at turn {n_turn}, introducing a change that contains the {new_attr} characteristic.",
    "Maintain the {old_attr1} and {old_attr2} fashion elements at turn {n_turn}, while adding a change that features the {new_attr} attribute.",
    "Preserve the {old_attr1} and {old_attr2} features at turn {n_turn}, with a change that includes the {new_attr} trait."
]

conflict = [
    "At turn {n_turn}, change only the {old_attr} attribute to {new_attr}, keeping the fashion attributes of other turns unchanged.",
    "In the {n_turn}th turn, replace the {old_attr} attribute with {new_attr} only, while maintaining other turns' fashion attributes as is.",
    "Modify the {old_attr} attribute to {new_attr} only at turn {n_turn}, keeping all other turns' fashion attributes intact.",
    "Only change the {old_attr} attribute to {new_attr} at turn {n_turn}, preserving the fashion attributes of the remaining turns.",
    "At turn {n_turn}, update the {old_attr} attribute to {new_attr} while leaving other turns' fashion attributes untouched.",
    "Change the {old_attr} attribute to {new_attr} only at turn {n_turn}, and keep the rest of the turns' fashion attributes unchanged.",
    "For turn {n_turn}, replace the {old_attr} attribute with {new_attr} only, maintaining all other fashion attributes as they are.",
    "In the {n_turn}th turn, modify just the {old_attr} attribute to {new_attr}, keeping other turns' fashion attributes unchanged.",
    "At turn {n_turn}, only update the {old_attr} attribute to {new_attr}, leaving all other turns' fashion attributes intact.",
    "Only change the {old_attr} attribute at turn {n_turn} to {new_attr}, while preserving other turns' fashion attributes.",
    "At the {n_turn}th turn, alter the {old_attr} attribute to {new_attr} exclusively, maintaining the rest of the turns' fashion attributes.",
    "Change only the {old_attr} attribute to {new_attr} at turn {n_turn}, keeping the fashion attributes of other turns intact.",
    "Modify the {old_attr} attribute at turn {n_turn} to {new_attr} only, leaving other turns' fashion attributes unchanged.",
    "At turn {n_turn}, switch the {old_attr} attribute to {new_attr} exclusively, while other turns' fashion attributes remain unchanged.",
    "Only replace the {old_attr} attribute at turn {n_turn} with {new_attr}, preserving all other turns' fashion attributes.",
    "At turn {n_turn}, update just the {old_attr} attribute to {new_attr}, keeping the other turns' fashion attributes intact.",
    "Change the {old_attr} attribute only at turn {n_turn} to {new_attr}, while maintaining the rest of the turns' fashion attributes.",
    "In turn {n_turn}, replace only the {old_attr} attribute with {new_attr}, keeping other turns' fashion attributes unchanged.",
    "Modify only the {old_attr} attribute at turn {n_turn} to {new_attr}, preserving all other turns' fashion attributes.",
    "At turn {n_turn}, change the {old_attr} attribute to {new_attr} exclusively, leaving other turns' fashion attributes untouched.",
    "Only update the {old_attr} attribute at turn {n_turn} to {new_attr}, while maintaining other turns' fashion attributes.",
    "Change only the {old_attr} attribute to {new_attr} at turn {n_turn}, keeping the rest of the turns' fashion attributes intact.",
    "At turn {n_turn}, replace the {old_attr} attribute exclusively with {new_attr}, preserving other turns' fashion attributes.",
    "Modify the {old_attr} attribute only at turn {n_turn} to {new_attr}, keeping the other turns' fashion attributes unchanged.",
    "In the {n_turn}th turn, change only the {old_attr} attribute to {new_attr}, while maintaining all other turns' fashion attributes.",
    "Only change the {old_attr} attribute at turn {n_turn} to {new_attr}, keeping other turns' fashion attributes intact.",
    "At turn {n_turn}, switch only the {old_attr} attribute to {new_attr}, leaving other turns' fashion attributes untouched.",
    "Change just the {old_attr} attribute to {new_attr} at turn {n_turn}, preserving the fashion attributes of the other turns.",
    "In the {n_turn}th turn, replace only the {old_attr} attribute with {new_attr}, while keeping other turns' fashion attributes the same.",
    "Only modify the {old_attr} attribute at turn {n_turn} to {new_attr}, maintaining the rest of the turns' fashion attributes.",
    "At turn {n_turn}, update only the {old_attr} attribute to {new_attr}, while other turns' fashion attributes remain unchanged.",
    "Change the {old_attr} attribute exclusively to {new_attr} at turn {n_turn}, keeping the rest of the turns' fashion attributes intact.",
    "Only replace the {old_attr} attribute with {new_attr} at turn {n_turn}, preserving all other turns' fashion attributes.",
    "At turn {n_turn}, modify only the {old_attr} attribute to {new_attr}, keeping the rest of the turns' fashion attributes unchanged.",
    "Change just the {old_attr} attribute at turn {n_turn} to {new_attr}, while maintaining other turns' fashion attributes.",
    "In the {n_turn}th turn, change only the {old_attr} attribute to {new_attr}, preserving the fashion attributes of other turns.",
    "Only update the {old_attr} attribute at turn {n_turn} to {new_attr}, leaving other turns' fashion attributes untouched.",
    "At turn {n_turn}, switch only the {old_attr} attribute to {new_attr}, maintaining other turns' fashion attributes.",
    "Change only the {old_attr} attribute at turn {n_turn} to {new_attr}, keeping the rest of the turns' fashion attributes unchanged.",
    "In turn {n_turn}, modify only the {old_attr} attribute to {new_attr}, while other turns' fashion attributes remain the same.",
    "Only change the {old_attr} attribute to {new_attr} at turn {n_turn}, preserving other turns' fashion attributes.",
    "At turn {n_turn}, replace only the {old_attr} attribute with {new_attr}, keeping all other turns' fashion attributes unchanged.",
    "Change the {old_attr} attribute exclusively at turn {n_turn} to {new_attr}, maintaining other turns' fashion attributes.",
    "Only modify the {old_attr} attribute at turn {n_turn} to {new_attr}, preserving the fashion attributes of the other turns.",
    "At turn {n_turn}, update only the {old_attr} attribute to {new_attr}, while keeping the other turns' fashion attributes intact.",
    "Change only the {old_attr} attribute to {new_attr} at turn {n_turn}, maintaining other turns' fashion attributes.",
    "In the {n_turn}th turn, replace only the {old_attr} attribute with {new_attr}, preserving all other turns' fashion attributes.",
    "Only change the {old_attr} attribute at turn {n_turn} to {new_attr}, while the rest of the turns' fashion attributes remain unchanged.",
    "At turn {n_turn}, modify only the {old_attr} attribute to {new_attr}, keeping other turns' fashion attributes the same."
]
