rollback = [
    "I really liked the {} fashion image you provided. Based on that, ",
    "The {} fashion image caught my eye—it’s just my style. Based on that, ",
    "That {} fashion image was exactly what I was looking for. Based on that, ",
    "I'm a fan of the {} fashion image you shared. Based on that, ",
    "The {} image you gave perfectly matched my fashion taste. Based on that, ",
    "I was impressed by the {} fashion image—it felt spot on. Based on that, ",
    "That {} outfit image resonated with my aesthetic. Based on that, ",
    "The {} fashion concept was very appealing to me. Based on that, ",
    "I loved the fashion vibe of the {} image you showed. Based on that, ",
    "The {} fashion sample stood out as my favorite. Based on that, ",
    "My favorite so far is the {} fashion image—it was great. Based on that, ",
    "The {} fashion design you generated was totally my style. Based on that, ",
    "I connected with the fashion mood of that {} image. Based on that, ",
    "I appreciated the fashion direction of the {} image. Based on that, ",
    "The fashion look in the {} image really worked for me. Based on that, ",
    "Out of everything, the {} fashion image felt the most authentic to my taste. Based on that, ",
    "The {} fashion illustration aligned perfectly with my preferences. Based on that, ",
    "The original fashion image had the exact vibe I wanted. Based on that, ",
    "I felt that the {} fashion image had the best style match. Based on that, ",
    "The {} image had a strong fashion impact on me—I liked it most. Based on that, ",
    "That very {} image had a style I truly connected with. Based on that, ",
    "I liked the look and feel of the {} fashion image the best. Based on that, ",
    "The fashion shown in the {} image really spoke to me. Based on that, ",
    "The {} image captured the exact aesthetic I love. Based on that, ",
    "I was drawn to the fashion elements in the {} picture. Based on that, ",
    "That {} outfit image felt the most relevant to my taste. Based on that, ",
    "I felt like the {} fashion image truly represented what I wanted. Based on that, ",
    "Among all, the {} one stood out for its stylish appeal. Based on that, ",
    "I liked the fashion direction shown in the {} concept. Based on that, ",
    "The {} fashion image was both stylish and inspiring. Based on that, ",
    "That {} image nailed the style I had in mind. Based on that, ",
    "The {} image reflected a strong sense of personal style I admire. Based on that, ",
    "The fashion in the {} image fit my taste better than the rest. Based on that, ",
    "I loved the elegance of the {} fashion concept. Based on that, ",
    "The {} outfit looked effortlessly cool—just how I like it. Based on that, ",
    "The fashion mood in the {} image caught my attention. Based on that, ",
    "The {} fashion design felt modern and stylish—just right. Based on that, ",
    "I loved the aesthetic direction in the very {} fashion image. Based on that, ",
    "The fashion in the {} image really matched my expectations. Based on that, ",
    "That {} image had the perfect combination of colors and style. Based on that, ",
    "I appreciated the style and creativity in the {} picture. Based on that, ",
    "The {} image gave off the right fashion-forward vibe. Based on that, ",
    "I was really happy with the look shown in the {} outfit. Based on that, ",
    "The original image matched the tone I was going for. Based on that, ",
    "The {} fashion sketch stood out as bold and tasteful. Based on that, ",
    "I liked the styling choices made in the {} concept. Based on that, ",
    "The {} image set a strong tone—it was just right. Based on that, ",
    "I still think the {} fashion image is the best of the bunch. Based on that, ",
]